cucapra/dahlia

buildbot/Pipfile, buildbot/buildbot/db.py, buildbot/buildbot/server.py
These changes remove the buildbot's dependency on [TinyDB](https://github.com/msiemens/tinydb), which was nice for getting started but maybe not so necessary anymore. Instead, the idea is to write a small `info.json` file *for every job* as an alternative to having one big database, which should be a bit simpler and more robust. To delete a job now, for example, you just have to delete its directory from the disk (no need to fiddle around with the database at all).
I'm mostly sure this works, but I'm not merging it quite yet so we can test it a little more.
=> Drop TinyDB

docs/indextype.md
I've written down a short proof showing accesses of an unrolled loop are the exact same as the original loop. I think the proof intuitively generalizes to n-dimension. Let me know if you are skeptical of any of the claims.
=> Proof of multidimensional acces safety and correctness

docs/indextype.md, src/error_msg.ml, src/type.ml
Error message "`Index must contain static information`" was appearing in examples `multaccess.sea` and `matadd.sea`, when it didn't make sense. Now:
- `multaccess.sea` is not rejected and correctly compiles to C (even thought it suffers the read-write problem, but this is not handled yet)
- `matadd.sea` is (hopefully correctly) rejected with a new error message: `[Type Error] array "c" has 1 dimension; attempted array access implies 2 dimensions`
Will resolve #4.
=> Multiple dimension array access bug fix

src/context.ml, src/dune, src/emit.ml, src/error_msg.ml, src/op_util.ml, src/type.ml
@tedbauer I'm enabling stricter checks for the project. The build system throws a few unused variable warnings now. Can you build this branch and change any intentional unused variables to `_`?
=> Enable unused variables warning

bin/seac.ml, src/ast.ml, src/compile_utils.ml, src/context.ml, src/context.mli, src/emit.ml, src/emit.mli, src/op_util.ml, src/op_util.mli, src/resolve_alias.ml, src/resolve_alias.mli, src/type.ml, src/type.mli, test/test_programs.ml, test/test_utils.ml, test/type_test.ml
Fixes #6.
This branch adds a new pass called `resolve_alias` that runs before the typechecker and replaces all instances of a `TAlias` with the exact type in the environment. This simplifies all the other phases which no longer need to handle the complicated delta threading logic.
=> Handle TAlias before type checking

Dockerfile, buildbot/Makefile, buildbot/Pipfile, buildbot/README.md, buildbot/buildbot/__init__.py, buildbot/buildbot/config_default.py, buildbot/buildbot/db.py, buildbot/buildbot/server.py, buildbot/buildbot/worker.py, buildbot/buildbot/workproc.py
This strategy uses a persistent, external process to execute the worker threads instead of running them in the same process as the Web server. In addition to being aesthetically nicer, this solves some important concurrency bugs where the server would kill workers without warning and we would sometimes have too many copies of the worker threads.
I'm pretty sure this is all working (works fine on my machine!), but I'll hold off on merging for now until I can try it out on Gorgonzola, which out through the weekend to expand its disk capacity.
=> Run buildbot worker threads in a separate process

src/emit.ml, src/error_msg.ml, src/lexer.mll, src/op_util.ml, src/parser.mly, src/type.ml, test/should-compile/typedefs.sea, test/should-compile/vsadd_nrl.sea, test/test_programs.ml, test/type_failures.ml, test/type_test.ml
Does this:
- Instead of parsing `int` in type annotations, parses `bit<n>`.
- When there are operations between single-value index types (i.e. index types with trivial static components), the resulting index type has a dynamic component that envelops both of the operands' dynamic ranges.
- The type strings in the error messages for index types now say `bit<n>` when appropriate.
Also updated the test files to have `bit<32>` annotations instead of `int`.
Closed the other PR and just did this in a fresh new branch.
**edit**: now emitted code includes `apcint.h` header and adds number of bits to `int` type annotations.
=> Arbitrary precision integers v2!

src/main/scala/Main.scala
This doesn't require `-f` to pass the file to parse; it's now a positional argument, so you type `./fuse file.sea` to compile. I also used scopt's `File` option type, which does some path-specific stuff.
=> scala: Use a simpler command-line syntax

src/main/scala/Emit.scala, src/main/scala/Errors.scala, src/main/scala/Parser.scala, src/main/scala/Syntax.scala, src/main/scala/TypeCheck.scala, src/main/scala/TypeEnv.scala, src/test/resources/should-compile/function.se, src/test/scala/ParsingPositive.scala, src/test/scala/TypeNegative.scala
Fixes #54 #62.
- Program structure is now a list of function defs followed by a list of decls, followed by top level commands.
- Applications consume array expressions completely
- Functions cannot return values (will potentially fix this in the future) and have return type `void`.
=> Function support

examples/errors/multiwrite.sea, src/main/scala/CodeGenHelpers.scala, src/main/scala/Compiler.scala, src/main/scala/Emit.scala, src/main/scala/Errors.scala, src/main/scala/Parser.scala, src/main/scala/RewriteView.scala, src/main/scala/Syntax.scala, src/main/scala/TypeCheck.scala, src/main/scala/Utils.scala, src/test/resources/should-compile/shrink-view-simple.se, src/test/resources/should-fail/multiwrite.se, src/test/scala/ParsingPositive.scala, src/test/scala/TestUtils.scala, src/test/scala/TypeNegative.scala, src/test/scala/TypePositive.scala
This PR implements `shrink` views and partially addresses #57.
Overview:
- Shrink view can be defined using `view v = a[0:w]` or `view v = a[n * i:w]`.
- In the second case `n * off`, `n` is the step size and **must be equal** to `w`. This is to make sure that programmer does trip with the stepping semantics of `shrink` views.
- Shrink views cannot be defined in an unroll context. This restriction can potentially be removed in the future.
- For an array `a: t[len bank b]...`, the view must have the same number of dimensions, the same type `t` and banking factor `b'` such that `b % b' == 0`. This also means that `shrink` views are always fully banked.
- A `view v = <view_type> arr...` expression completely consumes `arr` from the current context.
**TODO**
=> Implementation of shrink views

src/main/scala/Emit.scala, src/main/scala/Errors.scala, src/main/scala/Parser.scala, src/main/scala/RewriteView.scala, src/main/scala/Syntax.scala, src/main/scala/TypeCheck.scala, src/main/scala/TypeEnv.scala, src/test/scala/TypeCheckerSpec.scala
Fixes #76.
The type checker implements mostly we talked about in the meeting. The one new behavior is that both branches are required to use expressions that acquire capabilities in the same way. One branch cannot write into an array access while the other tries to read from it.
Also, this PR restructures `Environment` to better hide implementation details and even adds comments for it's methods!
=> Implement else branches

src/main/scala/Errors.scala, src/main/scala/TypeCheck.scala, src/test/scala/TypeCheckerSpec.scala
Addresses issue #70 . 
Checks if the array is unbanked (by checking if its banking factor is 1), and if it is, consumes bank 0.
Not sure about the error to throw here, or if bres * 1 is the correct mapping here.
=> adding TSizedInt rule for consumeBanks

fuse
@sampsyo or @sa2257 can you make sure this won't break buildbot setup? Once we have this, we can freely link `fuse` globally or put it on the path.
=> make `fuse` command insensitve to links

src/main/scala/Errors.scala, src/main/scala/Subtyping.scala, src/main/scala/Syntax.scala, src/main/scala/TypeCheck.scala, src/main/scala/TypeEnv.scala, src/test/scala/TypeCheckerSpec.scala
Fixes #53. Fixes #95. Fixes #87.
Three important things:
- Explicit subtyping hierarchy: sized int > idx types > static ints
- `let x = 1` `x` gets the type `TSizedInt(bitsNeeded(1))`.
- Only numbers and binary operations on numbers can a static type. So `a[0]` still works fine, but `let x = 1; a[x];` doesn't.
=> Subtyping is hard

docs/binders.md, docs/cpp-runnable.md, src/main/scala/Parser.scala, src/main/scala/RewriteView.scala, src/main/scala/Syntax.scala, src/main/scala/TypeCheck.scala, src/main/scala/backends/CppLike.scala, src/main/scala/backends/CppRunnable.scala, src/main/scala/backends/VivadoBackend.scala, src/test/scala/ParsingPositive.scala, src/test/scala/TypeCheckerSpec.scala
Add support for specifying external functions:
```
def extern print_vector(a: float[10]);
print_vector(a)
```
`extern` functions are only checked using their function signatures. Different backends can decide to do different things for each `extern`. `vivado` and `c++` remove all `extern` defs but keep calls to them. This allows us to use functions provided by header files.
Other backends might do different things for each `extern`. For example, a backend might decide to provide the implementation of `print_vector` in its implementation.
=> External functions

src/main/scala/TypeCheck.scala, src/test/scala/TypeCheckerSpec.scala
Fixes #51 
Creates a new scope in the environment; typechecks `c1`; extracts any new bindings from this typechecking; adds the new bindings to the initial environment and typechecks `c2`.
=> Fixing CSeq type checking rule

Dockerfile, buildbot/buildbot/server.py, buildbot/buildbot/state.py, buildbot/buildbot/static/style.css, buildbot/buildbot/templates/job.html, buildbot/buildbot/templates/joblist.html
As discussed in #32, and as requested by @rachitnigam, this adds a little popup on each job page that lets you manually change the state of a job. This is especially useful to "rewind" a failed job to an earlier stage to try it again after a code change.
=> buildbot: Interface to manually set a job's state

buildbot/buildbot/server.py
Quick fix for #126, which changed the state but neglected to tell the worker process that anything had changed.
=> buildbot: Notify workers when manually changing state

buildbot/buildbot/server.py, buildbot/buildbot/static/style.css, buildbot/buildbot/templates/files.html, buildbot/buildbot/templates/job.html, buildbot/buildbot/templates/log.html
As mentioned in #32, this makes the main job pages shorter and therefore less annoying to use. They link to separate pages for the file list and the log. The main job page still shows the last few messages from the log, but not the whole thing.
Here's what the new job page looks like:
=> buildbot: Move jobs' file lists and logs to separate subpages

build.sbt, src/main/scala/GenerateExec.scala, src/main/scala/Logger.scala, src/main/scala/Main.scala, src/main/scala/backends/VivadoBackend.scala, src/test/scala/RunTests.scala
Emit `skip_exit_check` for unroll pragmas. According to the manual:
`skip_exit_check`: An optional keyword that applies only if partial unrolling is specified with `factor=`. The elimination of the exit check is dependent on whether the loop iteration count is known or unknown:
- Fixed (known) bounds: No exit condition check is performed if the iteration count is a multiple of the factor. If the iteration count is not an integer multiple of the factor, the tool:
- Prevents unrolling.
- Issues a warning that the exit check must be performed to proceed.
- Variable (unknown) bounds: The exit condition check is removed as requested. You must ensure that:
- The variable bounds is an integer multiple of the specified unroll factor.
- No exit check is in fact required.
Fixes #127.
=> Skip exit checks in unrolled loops

buildbot/buildbot/db.py, buildbot/buildbot/server.py
Raise an appropriate error when requesting a specific job, and do not include corrupted job in the list of "all" jobs. This should let the buildbot keep on truckin' without a mysterious 500 error when something bad happens.
=> buildbot: Tolerate bad job JSON files

buildbot/buildbot/config_default.py, buildbot/buildbot/worker.py
[Based on #161, so the diff will look better after that's merged.]
The timeouts for compilation and synthesis are now in the buildbot's configuration, so they don't require editing hard-coded numbers to adjust anymore.
=> buildbot: Move timeouts to configuration

buildbot/buildbot/config_default.py, buildbot/buildbot/server.py, buildbot/buildbot/worker.py
As I was writing this, I realized that we can just set the platform and other flags in the Makefile itself. @sa2257 can just use the Makefiles while this is being tested (probably not today, I'm sick)
=> Expose hw target and sdsflags as curl options on buildbot

buildbot/buildbot/config_default.py, buildbot/buildbot/worker.py
=> buildbot: Provide executable name as TARGET argument to Makefile

.gitignore, docs/array-access-visualizer.md, docs/text-editors.md, tools/array-access-visualizer/examples.rkt, tools/array-access-visualizer/let-matrix.rkt, tools/array-access-visualizer/matrix-visualizer.rkt, website/i18n/en.json, website/sidebars.json
- Adds a racket library that can visualize array accesses
- Documentation about the library.
@tedbauer can use this when doing the fuse-rewrites to see what kinds of iteration patterns machsuite apps use.
=> Visualizing array accesses

buildbot/buildbot/worker.py
As #197 describes, when buildbot executes the compiled executable on the ZedBoard, we want the cwd to be the directory where the executable lives (i.e., `/mnt`). This way, the executable can look for its data files—which also live there—with relative paths.
=> buildbot: Change directory to /mnt to run executable

src/main/scala/TypeCheck.scala, src/test/scala/TypeCheckerSpec.scala
Currently, this program typechecks:
```
{
b[0] := 1;
---
a[0] := 1;
}
b[0] := 1
```
Intuitively, the hardware generated says that the big block executed in parallel with the final write. Since a parallel composed block has no guarantees about the schedule for the elements, the two writes to `b` might conflict.
This commit makes it so that each expression in a sequential composition is checked with the same initial environment but the total resources consumed by the sequential composition is the union of all resources consumed.
=> Parallel and Sequential composition

src/main/scala/backends/VivadoBackend.scala
On the topic of #211, this adds a short preamble to the Vivado backend that disables `ap_int` when compiling with a "normal" (non-HLS) compiler. For now, software compilation just uses `int` instead.
This is option "1a" in #211.
=> Add `ap_int` preamble to generated Vivado code

src/main/scala/Parser.scala, src/main/scala/backends/CppLike.scala, src/main/scala/backends/VivadoBackend.scala, src/main/scala/common/Syntax.scala, src/main/scala/passes/BoundsCheck.scala, src/main/scala/passes/CapabilityChecker.scala, src/main/scala/passes/Checker.scala, src/main/scala/passes/RewriteView.scala, src/main/scala/typechecker/TypeCheck.scala
OK. I feel the need to apologize for how hacky this solution is before I even start explaining it.
It's a huge hack and I'm sorry.
There we have it.
---
As per #211 (items 2 and 3), this adds a new `decor` (i.e., decoration) command, whose purpose is to insert arbitrary strings that are then inserted in to the generated source code. They have no semantics. You do this:
```
decor "#pragma SDS data copy(m1[0:row_size][0:col_size])"
```
and it inserts that `#pragma` directly into the generated C++. The idea is that, for evaluation purposes, we want to insert some pragmas into the HLS source code that we *never* intend to support as first-class language features. They're tool-specific garbage that is not interesting from a language/type system perspective; they're just annotations necessary …
=> Evaluation hack: decorations for inserting #pragmas into generated source

src/main/scala/Parser.scala, src/main/scala/backends/CppRunnable.scala, src/main/scala/backends/VivadoBackend.scala, src/main/scala/common/Syntax.scala, src/main/scala/passes/BoundsCheck.scala, src/main/scala/typechecker/Subtyping.scala, src/main/scala/typechecker/TypeCheck.scala, src/test/scala/TypeCheckerSpec.scala
- Signed and unsigned numbers are not comparable
- By default, signed numbers are inferred.
=> Support for unsigned bit numbers

src/main/scala/backends/VivadoBackend.scala
Just a little tweak in the spirit of #211. Following new support for `ubit` in #215, this extends our typedef-like hack that allows non-HLS compilation by mapping these to `unsigned int`.
=> Tiny fix: add type alias for `ap_uint` for SW compilation

src/main/scala/common/Errors.scala, src/main/scala/typechecker/TypeCheck.scala, src/test/scala/TypeCheckerSpec.scala
Fixes #225. It's a straightforward fix! Includes a test ensuring that this program does not type check:
```
def foo(a: bit<32>, b: bit<32>) {
}
foo(1);
```
Also a bonus spelling fix. :rocket:
=> Add check for argument length mismatch in function call

src/main/scala/backends/VivadoBackend.scala
Given the hack in https://github.com/cucapra/fuse-benchmarks/pull/109, we will have a drop-in replacement for this header in software, so we won't need the #ifdef in generated code.
=> Simplify the C++ preamble for Vivado backend

src/main/scala/backends/CppLike.scala, src/main/scala/backends/CppRunnable.scala, src/main/scala/backends/VivadoBackend.scala
For a long list of reasons, we'd like to run Fuse programs _independently_ through Vivado HLS, eschewing SDSoC altogether. This additional pragma makes it possible to do so while marking the "external interface" arguments (essentially, `decl`s) as being allocated to BRAMs. Otherwise, they don't seem to get memories at all; they just turn into wires connected to the outside world.
=> Generate the `#pragma HLS interface` annotation for Vivado HLS

src/main/scala/backends/CppLike.scala, src/main/scala/backends/VivadoBackend.scala
Now partitioning pragmas go in the function header and `let` rather than being part of the declaration. This solves both #230 and a related problem where pragmas following `let` declarations would go before the initializer and semicolon.
=> Fix #230 by putting partitioning pragmas in the proper place

buildbot/buildbot/worker.py
Small changes to fix the bug (sudo sh and shell=true can't coexist).
Extended the timeout time for hw_emu execution.
=> fixed the bug with execution stage, extend the timeout for hw_emu

src/main/scala/Parser.scala, src/main/scala/backends/CppLike.scala, src/main/scala/backends/CppRunnable.scala, src/main/scala/backends/VivadoBackend.scala, src/main/scala/common/Errors.scala, src/main/scala/common/Syntax.scala, src/main/scala/passes/BoundsCheck.scala, src/main/scala/passes/CapabilityChecker.scala, src/main/scala/passes/Checker.scala, src/main/scala/passes/RewriteView.scala, src/main/scala/typechecker/TypeCheck.scala, src/main/scala/typechecker/TypeEnv.scala, src/test/scala/TypeCheckerSpec.scala
Closes #224. The syntax looks like this:
```
def add(a: bit<32>, b: bit<32>): bit<32> {
return a + b;
}
```
Return type annotations are optional, so this remains valid syntax (and defines a function that returns void):
```
def add_and_ignore(a: bit<32>, b: bit<32>) {
a + b;
}
```
=> Add return values to functions

src/main/scala/Parser.scala, src/main/scala/backends/CppLike.scala, src/main/scala/backends/VivadoBackend.scala, src/main/scala/common/Errors.scala, src/main/scala/common/Syntax.scala, src/main/scala/passes/BoundsCheck.scala, src/main/scala/passes/Checker.scala, src/main/scala/passes/RewriteView.scala, src/main/scala/typechecker/TypeCheck.scala, src/test/scala/TypeCheckerSpec.scala
This Fuse code:
```
for (let i = 0..4) pipeline {
let a = 1 + 2;
let b = 3 + 4;
}
```
works and generated HLS code with a `#pragma HLS PIPELINE` annotation. This version:
```
for (let i = 0..4) pipeline {
let a = 1 + 2
---
let b = 3 + 4
}
```
fails with a message saying that pipelining is only allowed on non-sequenced loops.
=> Worst-effort pipelining

buildbot/buildbot/worker.py
Some minor fixes for f1 code.
- `source` can directly refer to the file path. No need to `cd` into a directory unless something weird is going on with F1. 
- `afi` file is generated right after the AFI stage starts (@ViviYe correct?). Just read the value once when polling for the command to finish.
=> Minor cleanup for F1 bb code

buildbot/buildbot/config_default.py, buildbot/buildbot/worker.py
set a new variable f1-executable-name (currently set to sdaccel) instead of assuming the executable name is host and run ./host.
=> executable name can now be customized

build.sbt, fuse, src/main/scala/backends/CppLike.scala, src/main/scala/backends/CppRunnable.scala, src/main/scala/backends/Document.scala, src/main/scala/backends/VivadoBackend.scala, src/main/scala/passes/Checker.scala, src/main/scala/typechecker/TypeCheck.scala, src/test/scala/FileTests.scala, src/test/scala/RunTests.scala, tools/vim/syntax/fuse.vim
- Add Document class from deprecated scala.text into source.
- Will allow for 2.13 migration and usage of scala.js.
=> Remove Kiama dependency

src/main/scala/Compiler.scala, src/main/scala/Main.scala, src/main/scala/backends/CppLike.scala, src/main/scala/backends/CppRunnable.scala, src/main/scala/backends/VivadoBackend.scala, src/main/scala/backends/futil/FutilAst.scala, src/main/scala/common/Configuration.scala, src/main/scala/common/Document.scala, src/main/scala/common/Pretty.scala
- Add `--pass-debug` to show AST state after a pass. The flag also displays mutable AST information like `Consumable` annotations and inferred types for debugging.
=> Implement pretty printer for Dahlia AST

src/main/scala/passes/LoopCheck.scala
This is the true loopfix. There is something wrong with nameMap in the last version.
NameMap need addScope and endScope methods within both `if` scopes and loop scopes (`while` and `for`). StateMap does not for `if` statements, but for loops it does.
That makes both last pull request of fixing (which does not create scope for nameMap at an `if` statement) and the old loop checker both wrong (which create scope for both nameMap and stateMap at an `if` statement).
=> fixed loop checker

src/main/scala/common/ScopeMap.scala, src/main/scala/passes/LoopCheck.scala, src/test/scala/TypeCheckerSpec.scala
Now if the index is completely the same at the dimension requires unrolling, loop checker says there is not have cross loop dependency, but it is not smart enough to check view.
=> quick fix to indexing of loop checker

src/main/scala/Compiler.scala, src/main/scala/backends/CppLike.scala, src/main/scala/common/Checker.scala, src/main/scala/common/EnvHelpers.scala, src/main/scala/common/Pretty.scala, src/main/scala/common/Syntax.scala, src/main/scala/common/Transformer.scala, src/main/scala/passes/BoundsCheck.scala, src/main/scala/passes/LowerForLoops.scala, src/main/scala/passes/RewriteView.scala, src/main/scala/typechecker/AffineCheck.scala, src/main/scala/typechecker/CapabilityChecker.scala, src/main/scala/typechecker/TypeCheck.scala
PR does a combination of things.
- Defines a new EPhysAccess AST node for representing physical accesses on
array which are *only* meant for internal compiler code generator
purposes. One day, we can expose these through user-facing syntax.
- No user facing syntax for generating these accesses.
- Stubbed out affine and capability checking.
- Rewrite `RewriteViews` pass using the `Transformer` interface.
=> Implement internal-only physical accesses

src/main/scala/Main.scala, src/main/scala/backends/VivadoBackend.scala, src/main/scala/backends/futil/FutilAst.scala, src/main/scala/backends/futil/FutilBackend.scala, src/main/scala/common/Configuration.scala
- Add a `--memory-interface` flag to customize the memory interfaces that Dahlia generates for Vivado.
- Change the Futil backend to emit external memories for `decls`
=> Vivado Customizable Mem Interfaces

src/main/scala/backends/futil/FutilBackend.scala
This passes in the kernel name of the configuration instead of a default string `"main"`.
So, when 
```
./fuse ./../futil/examples/dahlia/vectorized-add.fuse -n NewName -b futil --lower
```
is called, it produces: 
```
...
component NewName() -> () { ... }
``` 
However, it also means that the default would be "kernel" rather than "main," so what should we do here?
=> Allow for custom component name when lowering to FuTIL.

src/main/scala/backends/futil/FutilAst.scala, src/main/scala/backends/futil/FutilBackend.scala
This is the simplest way to currently add another dimension to FuTIL backend with the given setup. This will suffice for the VGG Net example, but as discussed, next steps are using row major lookup for scalability purposes.
I've confirm this lowers (with the FuTIL additions to the primitive library):
```
decl A: ubit<32>[8][8][8][8];
```
->
```
import "primitives/std.lib";
component main() -> () {
cells {
A0_0_0_0 = prim std_mem_d4_ext(32,8,8,8,8,4,4,4,4);
}
wires {
}
control {
empty
}
}
```
=> Add D4 memory to FuTIL backend.

src/main/scala/backends/futil/FutilAst.scala, src/main/scala/backends/futil/FutilBackend.scala
This is to support `nn.softmax` implementation for Relay to FuTIL lowering.
=> Add futil backend for exp.

src/main/scala/backends/futil/FutilAst.scala, src/main/scala/backends/futil/FutilBackend.scala
Rewrite backend to use the `@external(1)` attribute to externalize memories rather than using `*_ext`﻿ to externalize memories.
=> Futil Backend External Attributes

src/main/scala/Parser.scala, src/main/scala/backends/CppLike.scala, src/main/scala/backends/CppRunnable.scala, src/main/scala/backends/VivadoBackend.scala, src/main/scala/common/Configuration.scala, src/main/scala/common/Pretty.scala, src/main/scala/common/Syntax.scala, src/test/scala/ParsingPositive.scala, src/test/scala/TypeCheckerSpec.scala
Adds the following syntax for backend imports:
```
import c++("math.h") 
vivado("vivado_math.h")
futil("sqrt.futil") {
def sqrt(in: ubit<32>): ubit<32>;
}
```
=> Implement backend-specific imports

file-tests/should-futil/invoke-with-fixed-point.expect, file-tests/should-futil/invoke-with-fixed-point.fuse, src/main/scala/backends/futil/FutilBackend.scala
Originally, an earlier case `CLet(id, Some(TFixed(t, i, un)), Some(e)) => {` was being matched before the more specific criteria where `e == EApp`.
Fixes #353.
=> Fix `CLet` match ordering.

file-tests/should-lower/hoist.expect, file-tests/should-lower/hoist.fuse, src/main/scala/passes/HoistMemoryReads.scala, src/main/scala/passes/HoistSlowBinop.scala
Bunch of fixes for hoisting and a new test. Use `ListMap` instead of `Map` because `Map` does not generate statement in order of hoisting.
- recursively hoist index expressions
- use ListMap instead of Map to preserve insertion order
- add test for hoisting
Fixed #360.
=> Hoisting Fixes

file-tests/should-futil/fixed-point-multi-cycle.expect, src/main/scala/backends/futil/FutilAst.scala
Reasoning provided here: https://github.com/cucapra/calyx/pull/490#discussion_r622536177
=> Re-add `mult` to static timing map.

file-tests/should-futil/fixed-point-multi-cycle.expect, file-tests/should-futil/fixed-point-multi-cycle.fuse, src/main/scala/backends/futil/FutilBackend.scala
Writing to a register takes `1` cycle, and a `mult_pipe` takes 3 cycles for a total of 4 cycles. Thanks @rachitnigam for pointing out basic arithmetic to me.
Inadvertently fixes [Calyx 498](https://github.com/cucapra/calyx/issues/498).
=> Fix timing bug with multi-cycle.

src/main/scala/common/Transformer.scala
The transformer method for rewriting the funcDefs was not using a new scope causing definitions to bleed into the parent context. This PR fixes that.
Fixes #372.
=> Correctly rewrite function definitions

.gitignore, file-tests/should-futil/for.expect, src/main/scala/Utils.scala, src/main/scala/backends/calyx/Ast.scala
Temporarily revert changes to generate `comb group` in the Calyx backend on master so that the tests in the Calyx repo don't fail.
=> Revert combinational group generation

file-tests/should-futil/for.expect, src/main/scala/Utils.scala, src/main/scala/backends/calyx/Ast.scala
Bring back `comb group` generation in the Calyx backend.
=> Emit `comb group` for Calyx backend

file-tests/should-futil/sequentialize-reduce.expect, file-tests/should-futil/sequentialize-reduce.fuse, src/main/scala/passes/Sequentialize.scala
Bug found by the Calyx interpreter. The problem was that expressions
like `x += 10` were only considered to be defines and not uses which
meant the sequentializer would try to run something like the following
in parallel.
```
x = 10;
x += 10;
```
=> [Sequentialize] CReduce is both define and use.

file-tests/should-futil/fixed-point-multi-cycle.expect, file-tests/should-futil/for.expect, file-tests/should-futil/invoke-with-fixed-point.expect, file-tests/should-futil/invoke-with-memories.expect, file-tests/should-futil/invoke.expect, file-tests/should-futil/sequentialize-reduce.expect, runt.toml, src/main/scala/backends/calyx/Ast.scala, src/main/scala/backends/calyx/Backend.scala
Builds upon @paili0628's work on adding the new `ref cell` syntax to Calyx. Instead of manually inlining interface ports of memories, generates memory cells with `ref` in them.
=> Generate `ref cell` for memory arguments

file-tests/should-futil/for-multi-dim.expect, file-tests/should-futil/for-multi-dim.fuse, src/main/scala/backends/calyx/Backend.scala
I realized that the open PR I have in Calyx will only work if Dahlia maps to 2d, 3d, and 4d sequential mems. So I made some quick fixes to do that. 
Once we get this merged, I can update my current Calyx PR and see what fails.
=> always maps to seq-mems now

file-tests/should-futil/use-plus-equals.expect, file-tests/should-futil/use-plus-equals.fuse, src/main/scala/backends/calyx/Backend.scala
We need to pass mutli-cycle info for the `EArrAccess` case for `EmitExpr()` in the Calyx backend. Before we weren't and that was creating incorrect Calyx code for LeNet. 
I also added a test case that would have caught the error I was running into in LeNet (basically for when Dahlia has something like`A[i] += value`.  When translated into Calyx we have a register to store the variable value, but that register's `write_en` signal needs to be `A.read_done`. Before it was just `1'd1`.)
=> Pass mutli-cycle info (needed to fix LeNet)

docs/cheat.md, docs/types.md
Parts of the documentation seem to be incorrect/out-of-date. Updating the parts on types and views. Let me know if the updates are correct I'll edit if necessary
Summary of changes
1. Move the program structure section to the beginning. Felt this was a gocha when I first started trying out records and the compiler was failing.
2. Record literal, add semicolon at the end
3. Remove statement that says functions cannot have return types
4. Update with working examples in views section.
Note: I can't seem to lower views
---
1. Adding an example of `bit` and `ubit`
2. Floating Points example on auto inference is incorrect (bug?)
Compiling
```
let x = 1.0;
```
gives
```
// git.status = dirty, build.date = Sat Jan 06 22:05:58 IST 2024, git.hash = 8abb5e2
#include <ap_int.h>
extern "C" {
void …
```
=> Update documentation types and views

src/main/scala/Parser.scala, src/test/scala/ParsingPositive.scala
1. Make the parser use the same logic as Octal literals
2. Add tests for this scenario
Closes #411
=> Fix parsing issue of hex numbers in cast expr

src/main/scala/common/Errors.scala, src/main/scala/passes/WellFormedCheck.scala, src/test/scala/TypeCheckerSpec.scala
Closes #418 
Summary:
1. Implement the trait `Tracker` in `WFEnv`, to track function definitions
* I've kept the key as `Id -> FuncDef`. This could have been `Id -> Boolean`, but it seemed too specific to this scenario for the `WFEnv`
2. Add a `canHaveFunctionInUnroll` function which will check from the `env` if the function can be present inside a unrolled loop
3. Update existing test case (which had scalar arguments) and add a new test case (with an array in the argument)
=> Support unrolling functions with scalar arguments inside unrolled loops

file-tests/should-futil/emit-signed-op.expect, file-tests/should-futil/emit-signed-op.fuse, src/main/scala/backends/calyx/Backend.scala, src/main/scala/backends/calyx/Helpers.scala
This fixes point number 2 in #427 
Dahlia was emitting Calyx primitives incorrectly for signed ops.
eg)
```
decl a: bit<10>[128];
decl b: bit<10>[128];
decl c: bit<10>[128];
for (let i:bit<8>=0..128) {
c[i] := a[i] & b[i];
}
```
The Calyx IR contains a std_sand primitive
1. Modify the function `signed` in Helpers.scala to use the op to decide if a given op is signed or not
1. Match for op type `NumOp` and use the previous behaviour
2. Any other op type binary operator primitives are not signed eg) bitwise, comparison
3. Add an test with signed bit and binops for regression
=> Fix Calyx backend issue with emitting signed binops

file-tests/should-futil/emit-signed-op.expect, file-tests/should-futil/fixed-point-constant.expect, file-tests/should-futil/fixed-point-multi-cycle.expect, file-tests/should-futil/for-multi-dim.expect, file-tests/should-futil/for.expect, file-tests/should-futil/invoke-with-fixed-point.expect, file-tests/should-futil/invoke-with-memories.expect, file-tests/should-futil/invoke.expect, file-tests/should-futil/sequentialize-reduce.expect, file-tests/should-futil/use-plus-equals.expect, src/main/scala/backends/calyx/Ast.scala, src/main/scala/backends/calyx/Backend.scala
This PR modifies the Calyx backend and the way it deals with `@pos` annotations.
First, instead of the old `metadata` block the Calyx backend produces the new `sourceinfo` block, which contains a `FILES` map and a `POSITIONS` map. Second, the Calyx backend adds `@pos` annotations to groups and cells wherever possible, while previously it only added `@pos` annotations to control nodes.
NOTE: This PR also made `@pos` ids ignore column numbers (so Calyx constructs that come from the same line of Dahlia code have the same `@pos` id). If we want to include column numbers in the future, we can change this!
=> [Calyx backend] Modify `@pos` to use new Calyx sourceinfo format
