cucapra/dahlia

src/ast.ml, src/emit.ml, src/parser.mly, src/type.ml
=> Flatten sequence representation

bin/seac.ml, src/ast.ml, src/ast_visitor.ml, src/compile_utils.ml, src/context.ml, src/dune, src/emit.ml, src/error_msg.ml, src/flatten_seq.ml, src/infer_cap.ml, src/lexer.mll, src/parser.mly, src/resolve_alias.ml, src/type.ml, test/test_programs.ml, test/test_utils.ml, test/type_failures.ml, test/type_test.ml
=> Implement capabilities for arrays using linear types

README.md
This fixes a few writing bugs and expands on some detail about how to compile & run the Scala version of the compiler.
=> scala: README improvements

src/main/scala/Emit.scala, src/main/scala/Parser.scala, src/main/scala/Syntax.scala, src/main/scala/TypeCheck.scala, src/test/scala/ParsingPositive.scala, src/test/scala/TypeNegative.scala
Implement remaining binary ops. Fixes #59.
=> Op-pocalypse now

src/main/scala/Syntax.scala, src/main/scala/TypeCheck.scala, src/test/scala/TypeCheckerSpec.scala
=> Allow arithmetic on idx types

src/main/scala/Emit.scala, src/main/scala/Parser.scala, src/main/scala/RewriteView.scala, src/main/scala/Syntax.scala, src/main/scala/TypeCheck.scala, src/test/scala/ParsingPositive.scala, src/test/scala/TypeCheckerSpec.scala
=> While loops

build.sbt, src/main/scala/Emit.scala, src/main/scala/Errors.scala, src/main/scala/Parser.scala, src/main/scala/RewriteView.scala, src/main/scala/ScopeMap.scala, src/main/scala/Syntax.scala, src/main/scala/TypeCheck.scala, src/main/scala/TypeEnv.scala, src/main/scala/TypeInfo.scala, src/test/scala/ParsingPositive.scala, src/test/scala/TypeCheckerSpec.scala
=> Struct support

docs/cheat.md
Additional documentation about program structure.
=> Fixes #103.

src/main/scala/RewriteView.scala, src/main/scala/Utils.scala
Addresses https://github.com/cucapra/seashell/pull/71#discussion_r257100246
=> Monadic rewrite for RewriteViews

buildbot/.gitignore, buildbot/buildbot/server.py, buildbot/buildbot/state.py, buildbot/buildbot/static/style.css, buildbot/buildbot/templates/base.html, buildbot/buildbot/templates/joblist.html, buildbot/buildbot/worker.py
Three changes:
- Extract state information out.
- Rename some titles and change format for date.
- Add color labels for states
=> Buildbot UX fixes

src/main/scala/backends/VivadoBackend.scala
Explicitly generate dimensions for arrays.
=> fixes #116

website/i18n/en.json, website/siteConfig.js, website/static/css/code-block-buttons.css
Adding the [kill](https://www.algolia.com/doc/api-client/methods/search/) in the overkill.
=> Bringing search to docs by the power of machine learning

docs/text-editors.md, tools/emacs/README.md, tools/emacs/fuse-mode/fuse-mode.el
=> Emacs tools

build.sbt, src/main/scala/Logger.scala, src/main/scala/Main.scala, src/main/scala/Syntax.scala, src/main/scala/Utils.scala
This seems like a nice simple logging framework. It advertises seamless support with Scala.js. It is pretty simply to add logging for new types of objects. I've done this for Positionals so that you can log/warn fuse source locations.
=> Added scribe as a logging system, addresses #137

src/main/scala/Subtyping.scala, src/test/scala/TypeCheckerSpec.scala
=> Bools are comparable

build.sbt, src/main/scala/BoundsCheck.scala, src/main/scala/GenerateExec.scala, src/main/scala/Main.scala, src/test/scala/RunTests.scala
=> Improve runtime for run tests

buildbot/README.md, buildbot/buildbot/worker.py
Copying data to sd_card directory before it's copied over to FPGA. [test](http://gorgonzola.cs.cornell.edu:8000/jobs/a0YznOGWOVM.html)
Need to handle case where there's no datafiles to copy. [issue](http://gorgonzola.cs.cornell.edu:8000/jobs/eR1B6evg5Hg.html)
This PR is branched from #199
=> buildbot: Copy datafiles to FPGA

buildbot/README.md, buildbot/buildbot/config_default.py, buildbot/buildbot/templates/joblist.html, buildbot/buildbot/worker.py
Adding features to Buildbot
- hw_basename for make file runs
Not entirely satisfied. Names update only once the job is done.
- accepting directive files
Make file flow provides make command with file name, regular flow generates the command.
=> Buildbot features

.gitignore
add DS_store to .gitignore
(Also learning how to do a pull request)
=> Ignore stuffs

src/main/scala/backends/VivadoBackend.scala
Refer https://github.com/cucapra/fuse-benchmarks/issues/83
=> Restore SDSCC Macro

buildbot/buildbot/config_default.py, buildbot/buildbot/server.py, buildbot/buildbot/state.py, buildbot/buildbot/worker.py
edited buildbot to work with both f1 instance and sdsoc.
=> buildbot toolchain configuration

docs/binders.md, docs/cheat.md, docs/cpp-runnable.md, docs/imports.md, docs/testing.md, src/main/scala/Parser.scala, src/main/scala/common/Syntax.scala, src/test/scala/ParsingPositive.scala, src/test/scala/TypeCheckerSpec.scala, src/test/should-run/convolution-1d.fuse, src/test/should-run/convolution-with-aligned-view.fuse, src/test/should-run/dot-product-with-array-literal.fuse, src/test/should-run/dot-product.fuse, src/test/should-run/matadd.fuse, src/test/should-run/records.fuse, src/test/should-run/split-example.fuse
=> Remove externs

src/main/scala/Parser.scala, src/main/scala/backends/CppLike.scala, src/main/scala/common/Syntax.scala, src/main/scala/passes/Checker.scala, src/main/scala/passes/RewriteView.scala, src/main/scala/typechecker/Subtyping.scala, src/main/scala/typechecker/TypeCheck.scala, src/test/scala/TypeCheckerSpec.scala
Check if static int is the right sized int type
=> Sized check

src/main/scala/backends/futil/FutilAst.scala
=> Small fix to the futil syntax

src/main/scala/backends/CppLike.scala, src/main/scala/backends/VivadoBackend.scala, src/main/scala/common/Document.scala, src/test/should-compile/fully-unrolled-matrix-vector-mul.fuse, src/test/should-compile/function.fuse, src/test/should-compile/general-matrix-multiply-one-unroll.fuse, src/test/should-compile/matadd.fuse, src/test/should-compile/vsadd.fuse, src/test/should-compile/vvadd.fuse
fixes #201, fixes #270, fixes #269
=> Lots o pragmas

build.sbt, src/main/scala/Compiler.scala, src/main/scala/Parser.scala, src/main/scala/backends/CppRunnable.scala, src/main/scala/backends/VivadoBackend.scala, src/main/scala/backends/futil/FutilBackend.scala, src/main/scala/common/Checker.scala, src/main/scala/common/Document.scala, src/main/scala/common/Errors.scala, src/main/scala/common/MultiSet.scala, src/main/scala/common/Pretty.scala, src/main/scala/common/Syntax.scala, src/main/scala/passes/BoundsCheck.scala, src/main/scala/passes/RewriteView.scala, src/main/scala/typechecker/CapabilityChecker.scala, src/main/scala/typechecker/Gadget.scala, src/main/scala/typechecker/Info.scala, src/main/scala/typechecker/Subtyping.scala, src/main/scala/typechecker/TypeCheck.scala, src/main/scala/typechecker/TypeEnv.scala, src/test/scala/TypeCheckerSpec.scala
- Syntax: `bit<32>{2}[10 bank 5][10 bank 2]` creates a memory where each bank has two ports.
=> Support multi ported memories

docs/array-access-visualizer.md, docs/binders.md, docs/cheat.md, docs/cpp-runnable.md, docs/install.md, docs/literals.md, docs/overview.md, docs/testing.md, docs/text-editors.md, docs/types.md, website/Makefile, website/siteConfig.js
=> updated and cleaned up some documentation

src/main/scala/backends/futil/FutilAst.scala, src/main/scala/backends/futil/FutilBackend.scala, src/main/scala/typechecker/TypeCheck.scala
fixed backend to generate done hole assignments for groups and generate correct bitwidths for components
=> Generate assignments to done holes

file-tests/should-lower/mat.expect, file-tests/should-lower/nested.expect, src/main/scala/passes/Sequentialize.scala
Slightly smarter sequentialize pass that doesn't add `---` when the commands use different variables
=> Smart Sequentialize

src/main/scala/backends/futil/FutilBackend.scala
World's greatest pull request!!! This shows up in NTT. (Addition to FuTIL standard library coming in a different PR.)
=> Support the ^ operator in the FuTIL backend

src/main/scala/backends/futil/FutilAst.scala, src/main/scala/backends/futil/FutilBackend.scala
still in process of testing but backend should use different primitive function for different bit additions
=> extend diff bit

src/main/scala/backends/futil/FutilBackend.scala
=> format fixes

src/main/scala/backends/futil/FutilAst.scala, src/main/scala/backends/futil/FutilBackend.scala
Use bigint to allow the sizes of numbers to be as big as we want.
=> Arbitrarily sized numbers

file-tests/should-futil/for.expect, file-tests/should-futil/for.fuse, src/main/scala/backends/calyx/Ast.scala, src/main/scala/backends/calyx/Backend.scala, src/main/scala/common/Pretty.scala, src/main/scala/common/Syntax.scala, src/main/scala/common/Transformer.scala, src/main/scala/passes/HoistSlowBinop.scala, src/main/scala/passes/LowerForLoops.scala, src/main/scala/passes/LowerUnroll.scala
=> A `@bound` attribute to for loops

src/main/scala/backends/calyx/Ast.scala, src/main/scala/backends/calyx/Backend.scala
Change `EmitOutput` to return Optional done condition
=> backend cleanup

file-tests/should-futil/fixed-point-constant.expect, file-tests/should-futil/fixed-point-multi-cycle.expect, file-tests/should-futil/for.expect, file-tests/should-futil/invoke-with-fixed-point.expect, file-tests/should-futil/invoke-with-memories.expect, file-tests/should-futil/invoke.expect, file-tests/should-futil/sequentialize-reduce.expect, src/main/scala/backends/calyx/Backend.scala
Changed Calyx Backend to map 1d arrays to Sequential memories.
=> Map 1d arrays to Seq Mems

file-tests/should-futil/fixed-point-multi-cycle.expect, file-tests/should-futil/for-multi-dim.expect, file-tests/should-futil/for.expect, file-tests/should-futil/invoke-with-memories.expect, file-tests/should-futil/use-plus-equals.expect, src/main/scala/backends/calyx/Backend.scala
Small commit to prepare for https://github.com/cucapra/calyx/issues/1286
Also have the change ready for Calyx for when we push this.
=> Rename Seq Mem Ports

src/main/scala/typechecker/Subtyping.scala, src/test/scala/TypeCheckerSpec.scala
=> Handle TRecType in areEqual

src/main/scala/Parser.scala, src/main/scala/Utils.scala, src/main/scala/backends/CppLike.scala, src/main/scala/common/CodeGenHelpers.scala, src/main/scala/common/Errors.scala, src/main/scala/common/Pretty.scala, src/main/scala/common/Syntax.scala, src/main/scala/passes/BoundsCheck.scala, src/main/scala/passes/LowerUnroll.scala, src/main/scala/typechecker/AffineCheck.scala, src/main/scala/typechecker/Subtyping.scala, src/test/scala/ParsingPositive.scala, src/test/scala/TypeCheckerSpec.scala
Fixes #408 
Added new tests. Ran the existing unit test `sbt test` and integration tests with `runt`
=> BigInt in EInt to allow large literals in let

file-tests/should-futil/fixed-point-constant.expect, file-tests/should-futil/fixed-point-multi-cycle.expect, file-tests/should-futil/for-multi-dim.expect, file-tests/should-futil/for.expect, file-tests/should-futil/invoke-with-fixed-point.expect, file-tests/should-futil/invoke-with-memories.expect, file-tests/should-futil/invoke.expect, file-tests/should-futil/sequentialize-reduce.expect, file-tests/should-futil/use-plus-equals.expect, src/main/scala/backends/calyx/Ast.scala
This needs to be merged before [Calyx #1897](https://github.com/calyxir/calyx/pull/1897), but I still want to wait a little bit to make sure [Calyx #1897](https://github.com/calyxir/calyx/pull/1897) has overall approval.
=> Use `@promotable` instead of `@static`
